title: LLM-s for beginners
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://MilenaJoanna.github.io/FinalProjectVistulaLLM-sForBeginners

aux_links:
  Template Repository: https://github.com/MilenaJoanna/FinalProjectVistulaLLM-sForBeginners
